import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "@/components/global/footer";
import { Navbar } from "@/components/global/navbar";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/lib/provider";
import Banner from "@/components/global/banner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />
          <Banner />
          <Navbar />
          <div className="">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
